// Manually maintained interpolation IP layout. See docs/MANUAL_WORKFLOW.md.
`ifndef INTERP12_IP_LAYOUT_VH
`define INTERP12_IP_LAYOUT_VH
`define INTERP3_FIELD_BITS 40
`define INTERP3_SAMPLES 3
`define INTERP3_S_AXIS_TDATA_BITS 32
`define INTERP3_M_AXIS_TDATA_BITS 240
`define INTERP3_LATENCY 37
`define HB2_STAGE2_FIELD_BITS 40
`define HB2_STAGE2_SAMPLES 3
`define HB2_STAGE2_S_AXIS_TDATA_BITS 96
`define HB2_STAGE2_M_AXIS_TDATA_BITS 240
`define HB2_STAGE2_LATENCY 12
`define HB2_STAGE3_FIELD_BITS 40
`define HB2_STAGE3_SAMPLES 6
`define HB2_STAGE3_S_AXIS_TDATA_BITS 192
`define HB2_STAGE3_M_AXIS_TDATA_BITS 480
`define HB2_STAGE3_LATENCY 11
`endif
